language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_script:
  - 
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
script:
  - mvn clean verify
after_success:
  - ./.scripts/deploy-site.sh
  - ./.scripts/deploy.sh
