/**
 * The MIT License (MIT)
 * <p>
 * Copyright (c) 2014 the original author or authors.
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.wandrell.pattern.command;

/**
 * Interface for the command executor pattern. It is prepared to work with the
 * two command pattern interfaces existing on this same package: {@link Command}
 * and {@link ResultCommand}.
 * <p>
 * The executor's job is receiving one of these commands through its own
 * {@code execute} method and processing it by calling that same command's
 * {@code execute} method.
 * <p>
 * The only difference between both types of command is that
 * {@code ResultCommand} returns a value when executed, while {@code Command}
 * doesn't. This is reflected by the executor, as it contains two
 * {@code execute} methods.
 * <p>
 * For {@code Command} instances an {@link #execute(Command) execute(Command)}
 * method exists with a {@code void} return type. While for
 * {@code ResultCommand} instances another {@link #execute(ResultCommand)
 * execute(ResultCommand)} exists, returning the received command's return
 * value.
 * <p>
 * Both methods are expected to execute the command as soon as they receive it.
 * There can be additional operations, such as catching exceptions, injecting
 * dependencies or setting up the environment. But these should be minimal, and
 * never postpone the command's execution more than necessary.
 * 
 * @author Bernardo Martínez Garrido
 * @see Command
 * @see ResultCommand
 */
public interface CommandExecutor {

    /**
     * Executes the received {@code Command}.
     * <p>
     * Any exception thrown by the command is expected to be caught and handled
     * inside this method.
     * 
     * @param command
     *            the command to be executed
     */
    public void execute(final Command command);

    /**
     * Executes the received {@code ReturnCommand} and returns the value
     * generated by this operation.
     * <p>
     * Any exception thrown by the command is expected to be caught and handled
     * inside this method.
     * 
     * @param command
     *            the command to be executed
     * @param <V>
     *            the type to be returned
     * @return the command's return value
     */
    public <V> V execute(final ResultCommand<V> command);

    /**
     * Undoes the received {@code Command}.
     * <p>
     * Any exception thrown by the command is expected to be caught and handled
     * inside this method.
     * <p>
     * When calling this method if there is nothing to undo no exception is
     * expected, the execution process as usual.
     * 
     * @param command
     *            the command to be executed
     */
    public void undo(final UndoCommand command);

}
